### ISSUE TITLE
cal change

### ISSUE THREAD

**Issue by sterrehan** [projecthorus/sondehub-amateur-tracker#110]
can you change the cal PA0CAB lastfligt to PA0CAB memorial
He is nouw silant key
plays remove 15, PA0CAB-4FSK and 449, PA0CAB and 449, PA0CAB

Thanks pe1glg han van der sterre

**Comment by darksidelemm** [comment]
This should have been on the horusdemodlib repository, but I'll fix it here.
I'll change these callsigns all to PA0CAB-SK - hopefully this is OK!
