### ISSUE TITLE
Filter APRS payloads with altitude < 1.5km

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-amateur-tracker#13]
The APRS importer is resulting in a lot of payloads which are on the ground (even some cars... using the balloon icon... sigh) showing up and cluttering the list.

I would suggest that we have an option, enabled by default, which filters out any APRS payload (determined via the modulation field) which has a maximum altitude below 1500m (may need to tune this value). This should get rid of a lot of the noise.

**Comment by LukePrior** [comment]
Done
