### ISSUE TITLE
Listener Icon Description - Does not show 'Radio' Information

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/sondehub-amateur-tracker#34]
The uploader_radio field seems to be ignored when displaying listener information (e.g. when a listener icon is clicked). It currently shows software name/version information in the Radio field.

Suggest we show data as follows:

Software: software_name - software_version
Radio: uploader_radio
Antenna: uploader_antenna

**Comment by LukePrior** [comment]
Solved.
