### ISSUE TITLE
Nice to have: horizontal speed plot in Grafana

### ISSUE THREAD

**Issue by zanco** [projecthorus/sondehub-amateur-tracker#86]
During a summerstorm PD3EGE launched an 4fsk tracker. It would be really nice to re-view the horizontal speed in Grafana too.

https://grafana.v2.sondehub.org/d/HJgOZLq7k/basic?var-Payload=PD3EGE&from=1688545183000&to=now&orgId=1&refresh=1m

Thanks,

**Comment by darksidelemm** [comment]
Could you raise this over at https://github.com/projecthorus/sondehub-infra please - thats the more correct location for grafana issues.
