### ISSUE TITLE
Site vehicles not loading - JS Error

### ISSUE THREAD

**Issue by HoshenKadosh** [projecthorus/sondehub-amateur-tracker#98]
![image](https://github.com/projecthorus/sondehub-amateur-tracker/assets/47646557/e5ff59fb-584b-4cb5-885a-ab2fac0426ba)

**Comment by darksidelemm** [comment]
Not getting this error at the moment? Is this still happening for you?

**Comment by darksidelemm** [comment]
OK, this was fixed by @xssfox while I was sleeping :-)
Someone uploaded data with bad formatting, and it broke things.
